name       : perl-params-validate
version    : '1.29'
release    : 5
source     :
    - https://www.cpan.org/authors/id/D/DR/DROLSKY/Params-Validate-1.29.tar.gz : 49a68dfb430bea028042479111d19068e08095e5a467e320b7ab7bde3d729733
license    : Artistic-2.0
component  : programming.perl
summary    : Validate method/function parameters
description: |
    Validate method/function parameters
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
