name       : perl-params-validate
version    : 1.26
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Params-Validate-1.26.tar.gz : 821ac3cfa9715b94f60926faf316b9ff722785594b37036202371ad2303a72ed
license    : Artistic-2.0
component  : programming.perl
summary    : Validate method/function parameters
description: |
    Validate method/function parameters
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
