name       : perl-params-validate
version    : '1.31'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Params-Validate-1.31.tar.gz : 1bf2518ef2c4869f91590e219f545c8ef12ed53cf313e0eb5704adf7f1b2961e
homepage   : https://metacpan.org/pod/Params::Validate
license    : Artistic-2.0
component  : programming.perl
summary    : Params::Validate - Validate method/function parameters
description: |
    This module allows you to validate method or function call parameters to an arbitrary level of specificity. At the simplest level, it is capable of validating the required parameters were given and that no unspecified additional parameters were passed in.
builddeps  :
    - perl-module-build
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
